#pragma kernel CSMain1
#pragma kernel CSMain2

RWStructuredBuffer<int> buffer1;
RWStructuredBuffer<int> buffer2;

[numthreads(4,1,1)]
void CSMain1 (uint3 dispatchID : SV_DispatchThreadID, uint3 groupThreadID : SV_GroupThreadID)
{
    buffer1[dispatchID.x] = groupThreadID.x;
}

[numthreads(4,4,1)]
void CSMain2 (uint3 dispatchID : SV_DispatchThreadID)
{
    uint id = dispatchID.x + dispatchID.y * 8;
    buffer2[id] = id;
}
